name: slurm
summary: Slurm Workload Manager
description: |
  Slurm is an open source, fault-tolerant, and highly scalable cluster management and
  job scheduling system for large and small Linux clusters.

adopt-info: slurm

grade: stable
confinement: classic

base: core20

apps:
  logrotate:
    daemon: oneshot
    command: usr/sbin/logrotate $SNAP_COMMON/etc/logrotate.conf
    timer: "00:00-24:00/288"

  slurmdbd:
    command: bin/slurmdbd
    daemon: simple
    restart-condition: never

  slurmctld:
    command: bin/slurmctld
    daemon: simple
    restart-condition: never

  slurmd:
    command: bin/slurmd
    daemon: simple
    restart-condition: never

  slurmrestd:
    command: bin/slurmrestd
    daemon: simple
    restart-condition: never

  sacct:
    command: bin/sacct

  sacctmgr:
    command: bin/sacctmgr

  salloc:
    command: bin/salloc

  sattach:
    command: bin/sattach

  sbatch:
    command: bin/sbatch

  sbcast:
    command: bin/sbcast

  scancel:
    command: bin/scancel

  scontrol:
    command: bin/scontrol

  sdiag:
    command: bin/sdiag

  sinfo:
    command: bin/sinfo

  sprio:
    command: bin/sprio

  squeue:
    command: bin/squeue

  sreport:
    command: bin/sreport

  srun:
    command: bin/srun

  sshare:
    command: bin/sshare

  sstat:
    command: bin/sstat

  strigger:
    command: bin/strigger

  munged:
    daemon: simple
    command: bin/munged
    restart-condition: never
  munge:
    command: bin/munge
  unmunge:
    command: bin/unmunge
  remunge:
    command: bin/remunge
  mungekey:
    command: bin/mungekey

  version:
    command: bin/slurm-version

parts:
  slurm:
    after:
      - json-c
      - libyaml
      - http-parser
      - munge
      - slurm-bins
    plugin: autotools
    source: https://download.schedmd.com/slurm/slurm-20.11.3.tar.bz2
    build-packages:
      - libhdf5-dev
      - python-dev
      - libreadline-dev
      - liblua5.3-dev
      - libbz2-dev
      - bzip2
      - mysql-client
      - libmysqlclient-dev
      - liblz4-dev
      - libpmi1-pmix
      - freeipmi
      - rrdtool
      - libncurses5-dev
      - libglib2.0-dev
      - libibmad-dev
      - libibumad-dev
      - libcurl4-gnutls-dev
    stage-packages:
      - liblua5.3-dev
      - libmysqlclient-dev
      - libaec-dev
      - libhdf5-103
      - mailutils
      - util-linux
      - libibmad-dev
      - libibumad-dev
      - libbrotli1
      - libcurl3-gnutls
      - libnghttp2-14
      - libpsl5
      - librtmp1
      - libssh-4
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --localstatedir=/var/snap/slurm/common/etc/slurm
      - --sbindir=/slurm-bins
      - --disable-developer
      - --disable-debug
      - --enable-slurmrestd
      - --with-libcurl
      - --with-munge=/usr
      - --with-http-parser=${SNAPCRAFT_STAGE}/usr
      - --with-yaml=${SNAPCRAFT_STAGE}/usr
      - --with-json=${SNAPCRAFT_STAGE}/usr
      - --with-ofed=/usr
      - --with-hdf5
    override-build: |
      snapcraftctl build
      ldconfig -n /snap/slurm/current/lib/slurm
      snapcraftctl set-version `cat META  | grep Version | awk '{print $2}'`

  slurm-configurator:
    plugin: dump
    source: src/slurm-configurator/

  slurm-bins:
    plugin: dump
    source: src/slurm-bins/
    source-type: local

  munge:
    plugin: autotools
    source: https://github.com/dun/munge.git
    source-type: git
    source-tag: munge-0.5.14
    build-packages:
      - gcc
      - libssl-dev
      - autoconf
      - make
      - libtool
      - zlib1g-dev
      - libbz2-dev
      - libgcrypt20-dev
    stage-packages:
      - libbz2-1.0
      - zlib1g
      - libgcrypt20-dev
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --with-crypto-lib=libgcrypt
      - --with-logrotatedir=/etc/logrotate.d

  munge-customizations:
    plugin: dump
    source: src/munge/

  common:
    plugin: dump
    source: src/common/
    source-type: local

  http-parser:
    source: https://github.com/nodejs/http-parser.git
    plugin: make
    source-type: git
    source-tag: v2.9.4
    make-parameters:
      - PREFIX=/usr

  libyaml:
    source: https://github.com/yaml/libyaml.git
    plugin: autotools
    source-type: git
    source-tag: 0.2.5
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc

  json-c:
    source: https://github.com/json-c/json-c.git
    plugin: cmake
    source-type: git
    source-tag: json-c-0.14-20200419
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
        # TODO check the end path for this lib, looks weird

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/

  logrotate:
    plugin: autotools
    source: https://github.com/logrotate/logrotate.git
    source-tag: 3.18.0
    stage-packages:
      - bzip2
    build-packages:
      - libpopt-dev
      - libtool
      - xz-utils
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
    override-build: |
      autoreconf -fiv
      snapcraftctl build

  logrotate-conf:
    plugin: dump
    source: src/logrotate/
    stage:
      - etc/
