name: slurm
summary: Slurm Workload Manager
description: |
  Slurm is an open source, fault-tolerant, and highly scalable cluster management and
  job scheduling system for large and small Linux clusters.

adopt-info: slurm

grade: stable
confinement: classic

base: core20

apps:
  mysql:
    command: bin/start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    restart-condition: never

  munged:
    daemon: simple
    command: bin/munged
    restart-condition: never

  slurmdbd:
    command: bin/slurmdbd
    daemon: simple
    restart-condition: on-failure

  slurmctld:
    command: bin/slurmctld
    daemon: simple
    restart-condition: on-failure

  slurmd:
    command: bin/slurmd
    daemon: simple
    restart-condition: on-failure

  slurmrestd:
    command: bin/slurmrestd
    daemon: simple
    restart-condition: on-failure

  sacct:
    command: bin/sacct

  sacctmgr:
    command: bin/sacctmgr

  salloc:
    command: bin/salloc

  sattach:
    command: bin/sattach

  sbatch:
    command: bin/sbatch

  sbcast:
    command: bin/sbcast

  scancel:
    command: bin/scancel

  scontrol:
    command: bin/scontrol

  sdiag:
    command: bin/sdiag

  sinfo:
    command: bin/sinfo

  sprio:
    command: bin/sprio

  squeue:
    command: bin/squeue

  sreport:
    command: bin/sreport

  srun:
    command: bin/srun

  sshare:
    command: bin/sshare

  sstat:
    command: bin/sstat

  strigger:
    command: bin/strigger

  munge:
    command: bin/munge
  unmunge:
    command: bin/unmunge
  remunge:
    command: bin/remunge
  mungekey:
    command: bin/mungekey

  version:
    command: bin/slurm-version

parts:
  slurm:
    after:
      - json-c
      - libyaml
      - http-parser
      - munge
    plugin: dump
    source: https://download.schedmd.com/slurm/slurm-20.02.1.tar.bz2
    build-packages:
      - libhdf5-dev
      - python-dev
      - libreadline-dev
      - liblua5.3-dev
      - libbz2-dev
      - bzip2
      - mysql-client
      - libmysqlclient-dev
      - liblz4-dev
      - libpmi1-pmix
      - freeipmi
      - rrdtool
      - libncurses5-dev
      - libglib2.0-dev
      - libibmad-dev
      - libibumad-dev
      - libcurl4-gnutls-dev
    stage-packages:
      - liblua5.3-dev
      - libmysqlclient-dev
      - libaec-dev
      - libhdf5-103
      - mailutils
      - util-linux
      - libibmad-dev
      - libibumad-dev
      - libbrotli1
      - libcurl3-gnutls
      - libnghttp2-14
      - libpsl5
      - librtmp1
      - libssh-4
    stage:
      - bin/
      - share/
      - sbin/
      - include/
      - lib/
      - etc/
      - usr/
      - slurm-bins/
    prime:
      - bin/
      - share/
      - sbin/
      - include/
      - lib/
      - etc/
      - usr/
      - slurm-bins/
    override-build: |
      snapcraftctl build
      ./configure \
          --enable-slurmrestd \
          --with-libcurl \
          --with-munge=$SNAPCRAFT_STAGE/usr/local \
          --with-http-parser=$SNAPCRAFT_STAGE/usr/local \
          --with-yaml=$SNAPCRAFT_STAGE/usr/local \
          --with-json=$SNAPCRAFT_STAGE/usr/local \
          --prefix=$SNAPCRAFT_PART_INSTALL \
          --localstatedir=/var/snap/slurm/common/etc/slurm \
          --with-ofed=$SNAPCRAFT_STAGE/usr/local
      make -j$(nproc)
      make install
      ldconfig -n /snap/slurm/current/lib/slurm

      snapcraftctl set-version `cat META  | grep Version | awk '{print $2}'`

      mkdir $SNAPCRAFT_PART_INSTALL/slurm-bins
      for slurm_bin in \
         sacct sacctmgr salloc sattach \
         sbatch sbcast scancel scontrol \
         sdiag  sinfo sprio squeue sreport \
         srun sshare sstat strigger; do
          mv $SNAPCRAFT_PART_INSTALL/bin/$slurm_bin $SNAPCRAFT_PART_INSTALL/slurm-bins/;
      done;

      for slurm_bin in \
         slurmd slurmdbd slurmctld slurmstepd slurmrestd; do
          mv $SNAPCRAFT_PART_INSTALL/sbin/$slurm_bin $SNAPCRAFT_PART_INSTALL/slurm-bins/;
      done;

  boost:
    plugin: dump
    source: https://github.com/kyrofa/boost_tarball/raw/master/boost_1_59_0.tar.gz
    source-checksum: sha1/5123209db194d66d69a9cfa5af8ff473d5941d97
    # When building MySQL, the headers in the source directory 'boost/' are
    # required. Previously, using the 'copy' plugin, the whole archive was put
    # under 'boost/', making the headers reside in 'boost/boost/'. Due to a bug,
    # we now only stage the 'boost/' directory without moving it.
    #
    # Bug: https://bugs.launchpad.net/snapcraft/+bug/1757093
    stage:
      - boost/
    prime:
      - -*

  # mysql part - thanks to @kyrofa
  mysql:
    plugin: cmake
    source: https://github.com/mysql/mysql-server.git
    source-tag: mysql-5.7.28
    source-depth: 1
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/mysql-support-compile-time-disabling-of-setpriority.patch
    after: [boost, patches]
    cmake-parameters:
      - -DWITH_BOOST=$SNAPCRAFT_STAGE
      - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
      - -DCMAKE_INSTALL_PREFIX=/
      - -DBUILD_CONFIG=mysql_release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_EMBEDDED_SERVER=OFF
      - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
      - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
      - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
      - -DWITH_PARTITION_STORAGE_ENGINE=OFF
      - -DINSTALL_MYSQLTESTDIR=
    build-packages:
      - wget
      - g++
      - cmake
      - bison
      - libncurses5-dev
      - libaio-dev
      - libssl-dev
      - libnuma-dev
      - pkg-config
      - libmecab-dev
      - zlib1g-dev
    stage-packages:
      - libaio1
      - libgcc1
      - libnuma-dev
    stage:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server
      - -COPYING
    prime:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server

      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/myisam*
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress

  # Copy over our MySQL scripts
  mysql-customizations:
    plugin: dump
    source: src/mysql/

  patches:
    source: src/patches
    plugin: dump
    prime:
      - -*        
  munge:
    plugin: dump
    source: https://github.com/dun/munge.git
    source-type: git
    source-tag: munge-0.5.14
    build-packages:
      - gcc
      - libssl-dev
      - autoconf
      - make
      - libtool
      - zlib1g-dev
      - libbz2-dev
    stage-packages:
      - libc6
      - libbz2-1.0
      - zlib1g
    stage:
      - usr/
      - lib/
    prime:
      - usr/
      - lib/
    override-build: |
      snapcraftctl build
      ./bootstrap
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr/local
      make
      make install
  munge-customizations:
    plugin: dump
    source: src/munge/

  common:
    plugin: dump
    source: src/common/
    source-type: local

  http-parser:
    source: https://github.com/nodejs/http-parser.git
    plugin: dump
    source-type: git
    source-tag: v2.9.4
    build-packages:
      - make
      - gcc
      - libtool
      - autoconf
    stage:
      - usr/
    prime:
      - usr/
    override-build: |
      snapcraftctl build
      PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local make
      PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local make install
      PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local make library

  libyaml:
    source: https://github.com/yaml/libyaml.git
    plugin: dump
    source-type: git
    source-tag: 0.2.5
    build-packages:
      - make
      - gcc
      - autoconf
      - automake
      - libtool
      - autotools-dev
      - aclocal
    stage:
      - usr/
    prime:
      - usr/
    override-build: |
      snapcraftctl build
      ./bootstrap
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr/local
      make
      make install

  json-c:
    source: https://github.com/json-c/json-c.git
    plugin: cmake
    source-type: git
    source-tag: json-c-0.14-20200419
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/local
    stage:
      - usr/
    prime:
      - usr/

  slurm-configurator:
    plugin: python
    source: src/slurm-configurator/
    stage:
      - -lib64/
      - templates/
    override-build: |
      snapcraftctl build
      cp -r $SNAPCRAFT_PART_BUILD/templates $SNAPCRAFT_PART_INSTALL/

  slurm-bins:
    plugin: dump
    source: src/slurm-bins/
    source-type: local
